version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  build-and-test:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.18.2
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}


      # Download and cache dependencies
      - restore_cache:
          keys:
            - app-dependencies-{{ checksum "./app/server/package.json" }}-{{ checksum "./app/client/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - app-dependencies-

      # install server and client modules
      - run: npm run install-all

      - save_cache:
          paths:
            - ./node-server/node_modules
            - ./react-client/node_modules
          key: app-dependencies-{{ checksum "./app/server/package.json" }}-{{ checksum "./app/client/package.json" }}

      # build front and backend
      - run: npm build

      # # reset db
      # - run: cd node-server && npm run reset-data
      # run tests
      - run: npm run test-all
workflows:
  test-and-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - release
                - beta
                - master